// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIvGgskeT1MX-3L9rso3X-lPPdZtJtejc',
    appId: '1:991794062821:web:7eaf289addfd7ff74a7b0c',
    messagingSenderId: '991794062821',
    projectId: 'accountbuddyfinal',
    authDomain: 'accountbuddyfinal.firebaseapp.com',
    storageBucket: 'accountbuddyfinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_xL3WrorH8Vrg1YMK5Pq9GF07V-bo5u8',
    appId: '1:991794062821:android:c69bf885be733cec4a7b0c',
    messagingSenderId: '991794062821',
    projectId: 'accountbuddyfinal',
    storageBucket: 'accountbuddyfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq37vQlXD4wMTVzOFyR5tC1opKP8OfIxs',
    appId: '1:991794062821:ios:b1b58ef53eba20754a7b0c',
    messagingSenderId: '991794062821',
    projectId: 'accountbuddyfinal',
    storageBucket: 'accountbuddyfinal.appspot.com',
    iosClientId: '991794062821-k4juu7oh4hoibg0ve4b7mhvvuet6sog0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ad',
  );
}
